name: Build Signed Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android APK with Capacitor
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17

      - name: Decode Keystore File
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > release.keystore

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./frontend

      - name: Build React App
        run: yarn build
        working-directory: ./frontend

      - name: Sync Capacitor
        run: npx cap sync android
        working-directory: ./frontend

      - name: Copy Web Assets
        run: npx cap copy android
        working-directory: ./frontend

      - name: Make Gradle Executable
        run: chmod +x ./gradlew
        working-directory: ./frontend/android

      - name: Build Signed APK
        run: ./gradlew assembleRelease -Pandroid.injected.signing.store.file=../release.keystore -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}
        working-directory: ./frontend/android

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: PotBot-Signed-APK
          path: frontend/android/app/build/outputs/apk/release/app-release.apk
