# .github/workflows/build-android.yml

name: Build Android App Bundle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android App Bundle with Capacitor
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: yarn install

      - name: Build frontend
        working-directory: ./frontend
        run: yarn build

      - name: Sync Capacitor
        working-directory: ./frontend
        run: |
          yarn add @capacitor/core @capacitor/cli --dev
          npx cap sync android

      - name: Copy web assets to Android
        working-directory: ./frontend
        run: npx cap copy android

      - name: Build Android AAB
        working-directory: ./frontend/android
        run: ./gradlew bundleRelease

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.aab
          path: frontend/android/app/build/outputs/bundle/release/app-release.aab
